### ISSUE TITLE
Runing on Symfony 4 ?

### ISSUE THREAD

**Issue by GothShoot** [Monogramm/MonogrammProxmoxBundle#2]
Hello,

It's possible to make runnable on Symfony 4 ?

Thank's 😄

**Comment by madmath03** [comment]
Hi,

The bundle has been developed and tested for Symfony 3.4, which is the basically the bridge between Symfony 3 and Symfony 4, so in theory it should already be working with SF 4 (not tested on our side).

If you have tested this bundle with SF 4 and encountered any issues, could you please share them here so we can look into them ?

Thanks.

**Comment by GothShoot** [comment]
Hi,

for now, composer can't resolve dependency (he try a lot of hour) juste an edit of composer.json is probably the solution 😃

**Comment by madmath03** [comment]
Sorry for the huge delay, was kind of overwhelmed by other projects on the past months.
I just merged the PR you submitted. Thanks a lot @GothShoot !
